ZG.Store.Presentation/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ZG.Common.DTO;
using ZG.Domain.Concrete;
using ZG.Domain.DTO;
using ZG.Domain.Models;
using ZG.Application;
using ZG.Store.Presentation.ViewModels;
using Address = ZG.Common.DTO.Address;

namespace ZG.Store.Presentation.Controllers
{
    public class CartController : Controller
    {
        private IProductService _productService;
        private IOrderService _orderProcessor;

        public CartController(IProductService productService, IOrderService orderProcessor)
        {
            _productService = productService;
            _orderProcessor = orderProcessor;
        }

        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel { Cart = cart, ReturnUrl = returnUrl });
        }

        public PartialViewResult GetCartContent(CartIndexViewModel cartIndexViewModel)
        {
            return PartialView(cartIndexViewModel);
        }

        [HttpPost]
        public RedirectToRouteResult AddToCart(Cart cart, int id, string returnUrl)
        {
            Product product = _productService.GetProductById(id);

            if (product != null)
            {
                cart.AddItem(product, 1);
            }

            return RedirectToAction("Index", new{returnUrl});
        }

        [HttpPost]
        public JsonResult RemoveFromCart(Cart cart, int id, string returnUrl)
        {
            var product = _productService.GetProductById(id);
            if (product != null)
            {
                cart.RemoveLine(product);
            }

            return Json(new ProductIdQuantityAndCartSummary { ProductId = id, Quantity = 0, NumberOfItems = cart.NumerbOfItems, CartTotalValue = cart.ComputeTotalItems().ToString("c") });
        }

        [HttpPost]
        public JsonResult UpdateCart(Cart cart, int id, int quantity, string returnUrl)
        {
            var product = _productService.GetProductById(id);
            if (product != null)
            {
                cart.UpdateItem(product, quantity);
            }

            return Json(new ProductIdQuantityAndCartSummary { ProductId = id, Quantity = quantity, NumberOfItems = cart.NumerbOfItems, CartTotalValue = cart.ComputeTotalItems().ToString("c") });
        }
        
        public PartialViewResult Summary(Cart cart)
        {
            var viewModel = new SummaryViewModel { NumberOfItems = cart.NumerbOfItems, TotalValue = cart.ComputeTotalItems().ToString("c") };
            return PartialView(viewModel);
        }
    }
}

ZG.Store.Presentation/Controllers/CheckoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ZG.Common.DTO;
using ZG.Domain.Concrete;
using ZG.Domain.DTO;
using ZG.Domain.Models;
using ZG.Application;
using ZG.Store.Presentation.ViewModels;
using Address = ZG.Common.DTO.Address;

namespace ZG.Store.Presentation.Controllers
{
    public class CheckoutController : Controller
    {
        private IOrderService _orderProcessor;

        public CheckoutController(IOrderService orderProcessor)
        {
            _orderProcessor = orderProcessor;
        }

        public ViewResult Shipping(CheckoutDetails checkoutDetails)
        {
            return View(checkoutDetails.ShippingDetails);
        }

        [HttpPost]
        public ActionResult Shipping(Cart cart, CheckoutDetails checkoutDetails)
        {
            if (!cart.Lines.Any())
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }

            if (ModelState.IsValid)
            {
                return RedirectToAction("Billing");
            }
            else
            {
                return View("CartEmpty");
            }
        }

        public ViewResult Billing(Cart cart, CheckoutDetails checkoutDetails)
        {
            var billingViewModel = new BillingViewModel()
            {
                NewBillingAddress = new Address(),
                ExistingBillingAddress = checkoutDetails.PaymentInformation.BillingAdress,
                ShippingAddress = checkoutDetails.ShippingDetails.ShippingAddress
            };
            return View("Billing", billingViewModel);
        }

        public ViewResult ReviewOrder(Cart cart, CheckoutDetails checkoutDetails)
        {
            if (!cart.Lines.Any() || string.IsNullOrWhiteSpace(checkoutDetails.ShippingDetails.ShippingAddress.FullName) || string.IsNullOrWhiteSpace(checkoutDetails.PaymentInformation.BillingAdress.FullName))
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }

            if (ModelState.IsValid)
            { 
                var reviewOrderViewModel = new ReviewOrderViewModel {Cart = cart, CheckoutDetails = checkoutDetails};
                return View(reviewOrderViewModel);
            }
            else
            {
                return View("CartEmpty");
            }
        }

        [HttpPost]
        public ViewResult PlaceOrder(Cart cart, CheckoutDetails checkoutDetails)
        {
            if (ModelState.IsValid)
            {
                _orderProcessor.ProcessOrder(cart, checkoutDetails);
                cart.Clear();

                return View("OrderConfirmation");
            }
            else
            {
                var reviewOrderViewModel = new ReviewOrderViewModel { Cart = cart, CheckoutDetails = checkoutDetails };
                return View("ReviewOrder", reviewOrderViewModel);
            }
        }
    }
}

ZG.Store.Presentation/Controllers/ChildActionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.SessionState;
using ZG.Domain.Models;
using ZG.Application;
using ZG.Store.Presentation.ViewModels;
using ZG.Domain.Concrete;
using ZG.Common;

namespace ZG.Store.Presentation.Controllers
{
    [SessionState(SessionStateBehavior.Disabled)]
    public class ChildActionController : Controller
    {
        private IProductCategoryService _prodCategoryService;
        private IGeographyService _geographyService;

        public ChildActionController(IProductCategoryService categoryService, IGeographyService geographyService)
        {
            _prodCategoryService = categoryService;
            _geographyService = geographyService;
        }

        [ChildActionOnly]
        public PartialViewResult Paging(string action, string controller, string currentCagetory, int currentPageNumber, int totalPages)
        {
            var pagingViewModel = new PagingViewModel(action, controller, currentCagetory, currentPageNumber, totalPages, Url);

            return PartialView(pagingViewModel);
        }

        [ChildActionOnly]
        public PartialViewResult CategoryLinks(string category)
        {
            IEnumerable<string> categories = _prodCategoryService.GetActiveCategoryNames();
            var model = new CategoriesViewModel { Categories = categories, SelectedCategory = category };

            return PartialView(model);
        }

        [ChildActionOnly]
        public PartialViewResult CategoryDropdown(string category)
        {
            IEnumerable<string> categories = _prodCategoryService.GetActiveCategoryNames();
            var model = new CategoriesViewModel { Categories = categories, SelectedCategory = category };

            return PartialView(model);
        }

        [ChildActionOnly]
        public PartialViewResult CheckoutBreadCrumbs(string activeCrumb)
        {
            if (string.Compare(activeCrumb, "shipping", true) == 0)
            {
                ViewBag.ActiveCrumb = CheckoutBreadCrumb.Shipping;
            }
            else if (string.Compare(activeCrumb, "billing", true) == 0)
            {
                ViewBag.ActiveCrumb = CheckoutBreadCrumb.Billing;
            }
            else if (string.Compare(activeCrumb, "revieworder", true) == 0)
            {
                ViewBag.ActiveCrumb = CheckoutBreadCrumb.ReviewOrder;
            }

            return PartialView();
        }

        [ChildActionOnly]
        public PartialViewResult States(int? id)
        {
            var states = _geographyService.GetStates();

            var stateViewModel = new StatesViewModel { States = states, StateId = id };
            return PartialView(stateViewModel);
        }

        [ChildActionOnly]
        public PartialViewResult Provinces(int? id)
        {
            var provinces = _geographyService.GetProvinces();

            var provinceViewModel = new ProvincesViewModel { Provinces = provinces, ProvinceId = id };
            return PartialView(provinceViewModel);
        }

        [ChildActionOnly]
        public PartialViewResult USCanada(int? id)
        {
            var usCanada = _geographyService.GetUSAndCanada();

            var viewModel = new USCanadaViewModel { USCanada = usCanada, CountryId = id };
            return PartialView(viewModel);
        }
    }
}

ZG.Store.Presentation/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.SessionState;
using ZG.Application;
using ZG.Store.Presentation.ViewModels;

namespace ZG.Store.Presentation.Controllers
{
    public class ProductController : Controller
    {
        private IProductService _productService;
        private int _pageSize = 4;

        public ProductController(IProductService productService)
        {
            _productService = productService;
        }

        public ViewResult List(string category, int page = 1)
        {
            var porductsPerPage = _productService.GetActiveProducts(category, page, _pageSize);

            var productListViewModel = new ProductListViewModel
                {
                    Products = porductsPerPage.Products,
                    CurrentPageNum = page,
                    RecordsPerPage = _pageSize,
                    TotalPages = (int)Math.Ceiling((decimal)porductsPerPage.TotalProducts / _pageSize),
                    CurrentCategory = category
                };


            return View(productListViewModel);
        }

        public ViewResult Details(int id)
        {
            var prod = _productService.GetProductById(id);
            return View(prod);
        }
    }
}

ZG.Store.Presentation/Views/Shared/Address.cshtml
@model ZG.Common.DTO.Address

<div>@Html.DisplayFor(m => m.FullName)</div>
<div>@Html.DisplayFor(m => m.Address1)</div>
@if (!string.IsNullOrWhiteSpace(Model.Address2))
{
    <div>@Html.DisplayFor(m => m.Address2)</div>
}
<div>@Html.DisplayFor(m => m.City), 
    @if(Model.StateId > 0)
    {
        @Html.DisplayFor(m => m.State) 
    }
    else 
    {
        @Html.DisplayFor(m => m.Province) 
    } 
    @Html.DisplayFor(m => m.Zip)
</div>
<div>@Html.DisplayFor(m => m.CountryId)</div>
<div>@Html.DisplayFor(m => m.Phone)</div>

ZG.Store.Presentation/Views/Shared/CartDetails.cshtml
@model IEnumerable<ZG.Domain.Concrete.CartLine>

@foreach (var cartLine in Model)
{
    <div>@cartLine.Product.Name</div>
    <div>@cartLine.Product.Price.ToString("c")</div>
    <div>Quantity: @cartLine.Quantity</div>

}

ZG.Store.Presentation/Views/Shared/CheckoutBreadCrumbs.cshtml
@using ZG.Common;

@if (ViewBag.ActiveCrumb != CheckoutBreadCrumb.Shipping)
{
    @Html.ActionLink("Shipping", "Shipping", "Checkout")
}
else
{
    @:Shipping
}

> 

@if (ViewBag.ActiveCrumb != CheckoutBreadCrumb.Billing)
{
    @Html.ActionLink("Payment", "Billing", "Checkout")
}
else
{
    @:Payment
}

> 

@if (ViewBag.ActiveCrumb != CheckoutBreadCrumb.ReviewOrder)
{
    @Html.ActionLink("Place Order", "ReviewOrder", "Checkout")
}
else
{
    @:Place Order
}

ZG.Store.Presentation/Views/Shared/OrderSummary.cshtml
@model ZG.Domain.Concrete.Cart

<h2>Order Summary</h2>
@if(Model.NumerbOfItems > 0)
{
    <div>Items (@Model.NumerbOfItems): @Model.ComputeTotalItems().ToString("c")</div> 
    <div>Shipping & Handling: @Model.ComputeShippingAndHandling().ToString("c")</div>
    <hr />
    <div>Total before tax: @Model.ComputeTotalBeforeTax().ToString("c")</div>
    <div>Estimated tax to be collected: @Model.ComputeTax().ToString("c")</div>
    <hr />
    <div>Order total: @Model.ComputeOrderTotal().ToString("c")</div>
}

ZG.Store.Presentation/Views/Shared/PaymentInformation.cshtml
@model ZG.Domain.Concrete.CheckoutDetails

<h2>TODO: add payment infor here</h2>
<h3>Billing address</h3>

@if (Model.IsBillingAddressSameAsShippingAddress())
{
    @:Same as shipping address 
}
else
{
    @Html.Partial("Address", Model.PaymentInformation.BillingAdress)
}

@Html.ActionLink("Change", "Billing", "Checkout")

ZG.Store.Presentation/Views/Shared/ProductSummary.cshtml
@model ZG.Domain.DTO.ProductBriefInfo

<div class="item">
    <div>@Html.ActionLink(Model.Name, "Details", "Product", new{id = Model.Id}, null) </div>
    <div>@Model.Description </div>
    <div>@Html.ActionLink(Model.Price.ToString("c"), "Details", "Product", new{id = Model.Id}, null) </div>
</div>

ZG.Store.Presentation/Views/Shared/ShippingSpeed.cshtml
<h2>Shipping Speed Options Goes Here</h2>

ZG.Store.Presentation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("your logo here", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    @Html.Action("Summary", "Cart")
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.RouteLink("Home", "Products")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>

        <div id="body">
            @RenderSection("featured", false)
            <div class="colmask threecol">
                <div class="colmid">
                    <div class="colleft">
                        <div class="col1">
				            @RenderBody()
                        </div>
                        <div class="col2">
                            <div id="categories">
                                @{ Html.RenderAction("Categories", "ChildAction" );}
                            </div>
                        </div>
                        <div class="col3">
                            @RenderSection("rightColumn", false)
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>

ZG.Store.Presentation/Views/Shared/_Layout1Col.cshtml
@{
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<div class="col-container">
    <div class="col">
        @RenderBody()
    </div>
</div>

@section featured {
    @RenderSection("featured", false)
}

@section scripts {
    @RenderSection("scripts", false)
}

ZG.Store.Presentation/Views/Shared/_Layout2Col.cshtml
@{
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<div class="col-container">
    <div class="col1">
        Left Col
        @RenderSection("leftColumn", false)
    </div>
    <div class="col2">
        @RenderBody()
    </div>
</div>

@section featured {
    @RenderSection("featured", false)
}

@section scripts {
    @RenderSection("scripts", false)
}

ZG.Store.Presentation/Views/Shared/_Layout3Col.cshtml
@{
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<div class="colmask threecol">
    <div class="colmid">
        <div class="colleft">
            <div class="col1">
                @RenderBody()
            </div>
            <div class="col2">
                <div id="categories">
                    @{ Html.RenderAction("CategoryLinks", "ChildAction");}
                </div>
            </div>
            <div class="col3">
                @RenderSection("rightColumn", false)
            </div>
        </div>
    </div>
</div>

@section featured {
    @RenderSection("featured", false)
}

@section scripts {
    @RenderSection("scripts", false)
}

ZG.Store.Presentation/Views/Shared/_LayoutMain.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/coffee")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("your logo here", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    @Html.Action("Summary", "Cart")
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.RouteLink("Home", "Products")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>

        <div id="body">
            @RenderSection("featured", false)
            @RenderBody()
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - G&Z Trading Inc.</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", false)
    </body>
</html>